"""
Visual Generation Agent
────────────────────────
Generates one AI image per scene using the Pixazo API (Flux 1 Schnell model).

Model choice: Flux 1 Schnell
  • Price:    $0 (completely free)
  • API:      Synchronous — returns the image URL directly (no polling loop)
  • Quality:  Fast, photorealistic, cinematic
  • Endpoint: POST https://gateway.pixazo.ai/flux-1-schnell/v1/getData
  • Auth:     Header: Ocp-Apim-Subscription-Key: <api_key>

Fallback model: Flux 2 Klein
  • Price:    $0.0007 / 1024×1024 image
  • API:      Synchronous (also returns URL directly)
  • Endpoint: POST https://gateway.pixazo.ai/flux-2-klein-4b/v1/generateImage

Each scene receives a rich, Flux-optimised image prompt generated by
script_agent.generate_scene_image_prompts() — no stock photo attribution needed.

API key: Set PIXAZO_API_KEY in .env
Get your free key at: https://api-console.pixazo.ai/api_keys
"""

import time
from pathlib import Path

import requests
from tenacity import retry, stop_after_attempt, wait_exponential

from utils.logger import logger
from config.settings import settings

# ── Pixazo API endpoints ──────────────────────────────────────────────────────
# Flux 1 Schnell — FREE, synchronous
_SCHNELL_URL = "https://gateway.pixazo.ai/flux-1-schnell/v1/getData"

# Flux 2 Klein — ~$0.0007/image, better quality, also synchronous
_KLEIN_URL = "https://gateway.pixazo.ai/flux-2-klein-4b/v1/generateImage"

# Portrait 9:16 dimensions for Instagram Reels.
# 720×1280 generates crisp portrait images that fill the 1080×1920 Reel frame.
_IMG_WIDTH = 720
_IMG_HEIGHT = 1280

# Brief delay between generation calls to avoid hitting rate limits
_INTER_REQUEST_DELAY = 1.5


def _headers() -> dict[str, str]:
    return {
        "Content-Type": "application/json",
        "Cache-Control": "no-cache",
        "Ocp-Apim-Subscription-Key": settings.pixazo_api_key,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Core generation helpers
# ─────────────────────────────────────────────────────────────────────────────

@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=2, min=3, max=20),
    reraise=True,
)
def _generate_schnell(prompt: str) -> str:
    """
    Generate an image with Flux 1 Schnell (FREE).
    Returns the CDN URL of the generated image.
    """
    payload = {
        "prompt": prompt,
        "num_steps": 4,        # Schnell max is 8; 4 is optimal speed/quality
        "width": _IMG_WIDTH,
        "height": _IMG_HEIGHT,
    }
    response = requests.post(_SCHNELL_URL, headers=_headers(), json=payload, timeout=60)
    response.raise_for_status()
    data = response.json()
    url = data.get("output")
    if not url:
        raise ValueError(f"Pixazo Flux Schnell returned unexpected response: {data}")
    return url


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=2, min=3, max=20),
    reraise=True,
)
def _generate_klein(prompt: str) -> str:
    """
    Generate an image with Flux 2 Klein (~$0.0007/image, higher quality).
    Returns the CDN URL of the generated image.
    """
    payload = {
        "prompt": prompt,
        "steps": 25,
        "width": _IMG_WIDTH,
        "height": _IMG_HEIGHT,
    }
    response = requests.post(_KLEIN_URL, headers=_headers(), json=payload, timeout=90)
    response.raise_for_status()
    data = response.json()
    url = data.get("output")
    if not url:
        raise ValueError(f"Pixazo Flux Klein returned unexpected response: {data}")
    return url


def _download_image(url: str, dest: Path) -> Path:
    """Stream-download a generated image from its CDN URL and save locally."""
    response = requests.get(url, timeout=60, stream=True)
    response.raise_for_status()
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "wb") as f:
        for chunk in response.iter_content(chunk_size=16_384):
            f.write(chunk)
    return dest


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def generate_image_from_prompt(
    prompt: str,
    output_path: Path,
    use_quality_model: bool = False,
) -> Path:
    """
    Generate one AI image from a scene prompt and save it locally.

    Primary:  Flux 1 Schnell (free)
    Fallback: Flux 2 Klein   (if Schnell fails, or use_quality_model=True)

    Args:
        prompt:             Flux-optimised cinematic image generation prompt.
        output_path:        Destination file path (.jpg recommended).
        use_quality_model:  If True, skip Schnell and use Klein directly.

    Returns:
        Path to the saved image file.

    Raises:
        ValueError:   If PIXAZO_API_KEY is not configured.
        RuntimeError: If all generation attempts fail.
    """
    if not settings.pixazo_api_key:
        raise ValueError(
            "PIXAZO_API_KEY is not set in .env. "
            "Get your free key at: https://api-console.pixazo.ai/api_keys"
        )

    if not use_quality_model:
        try:
            img_url = _generate_schnell(prompt)
            path = _download_image(img_url, output_path)
            logger.debug("Flux Schnell → %s", output_path.name)
            return path
        except Exception as exc:
            logger.warning("Flux Schnell failed (%s). Trying Flux Klein fallback...", exc)

    # Fallback / quality mode: Flux 2 Klein
    try:
        img_url = _generate_klein(prompt)
        path = _download_image(img_url, output_path)
        logger.debug("Flux Klein → %s", output_path.name)
        return path
    except Exception as exc:
        raise RuntimeError(
            f"Both Pixazo models failed for scene image. "
            f"Check your API key and network connection. Last error: {exc}"
        ) from exc


def generate_scene_images(
    image_prompts: list[str],
    output_dir: Path,
    run_id: str,
    use_quality_model: bool = False,
) -> list[Path]:
    """
    Generate one AI image per scene from the image prompts list.

    Args:
        image_prompts:      List of Flux-optimised cinematic prompts (one per scene).
        output_dir:         Directory to save generated images.
        run_id:             Unique run identifier used in filenames.
        use_quality_model:  If True, use Flux Klein over Schnell for all scenes.

    Returns:
        Ordered list of local image Paths (one per scene).
        If a scene fails after retries, the previous scene's image is reused.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    image_paths: list[Path] = []

    for i, prompt in enumerate(image_prompts):
        dest = output_dir / f"{run_id}_scene_{i + 1:02d}.jpg"

        # Skip regeneration if file already exists (pipeline retry safety)
        if dest.exists():
            logger.debug("Scene %d image cached, skipping generation.", i + 1)
            image_paths.append(dest)
            continue

        try:
            path = generate_image_from_prompt(
                prompt, dest, use_quality_model=use_quality_model
            )
            image_paths.append(path)
            logger.info("Scene %d/%d image generated.", i + 1, len(image_prompts))
            # Throttle between requests
            if i < len(image_prompts) - 1:
                time.sleep(_INTER_REQUEST_DELAY)
        except Exception as exc:
            logger.error("Failed to generate image for scene %d: %s", i + 1, exc)
            if image_paths:
                logger.warning("Reusing previous scene image as placeholder for scene %d.", i + 1)
                image_paths.append(image_paths[-1])
            else:
                raise

    logger.info("Generated %d scene images via Pixazo Flux API.", len(image_paths))
    return image_paths
